'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource_en_AU
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SlardarFileSearcher.Resource_en_AU", GetType(Resource_en_AU).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Press any key to exit. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ExitText() As String
            Get
                Return ResourceManager.GetString("ExitText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Input extension name for exclude, split by comma(,), DO NOT INPUT DOT(.) 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ExtensionIgnore() As String
            Get
                Return ResourceManager.GetString("ExtensionIgnore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Extension for ignore:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ExtensionIgnoreText() As String
            Get
                Return ResourceManager.GetString("ExtensionIgnoreText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Input extension name for searching, split by comma(,), DO NOT INPUT DOT(.), * or empty means search all files 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ExtensionSearch() As String
            Get
                Return ResourceManager.GetString("ExtensionSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Extension for search: 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ExtensionSearchText() As String
            Get
                Return ResourceManager.GetString("ExtensionSearchText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Find text in file:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property FindInFile() As String
            Get
                Return ResourceManager.GetString("FindInFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 text was found in files:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property FindInFileList() As String
            Get
                Return ResourceManager.GetString("FindInFileList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Choose root folder for search: 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property FolderBrowserDialogDescription() As String
            Get
                Return ResourceManager.GetString("FolderBrowserDialogDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Input the folder name for exclude, split by comma(,), DO NOT INPUT DOT(.) 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property FolderIgnore() As String
            Get
                Return ResourceManager.GetString("FolderIgnore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Folder for ignore:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property FolderIgnoreText() As String
            Get
                Return ResourceManager.GetString("FolderIgnoreText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Selected folder is not exits. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property FolderNotExits() As String
            Get
                Return ResourceManager.GetString("FolderNotExits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Illegal size of file, pelase try again 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property IllegalSizeText() As String
            Get
                Return ResourceManager.GetString("IllegalSizeText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Input max size of file, 0 means no limit 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property MaxFileSize() As String
            Get
                Return ResourceManager.GetString("MaxFileSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Max size:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property MaxFileSizeText() As String
            Get
                Return ResourceManager.GetString("MaxFileSizeText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Write result file error:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property OutputError() As String
            Get
                Return ResourceManager.GetString("OutputError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Read file failed:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ReadFileFailed() As String
            Get
                Return ResourceManager.GetString("ReadFileFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Read folder failed: 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ReadFolderFailed() As String
            Get
                Return ResourceManager.GetString("ReadFolderFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Reading file:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ReadingFile() As String
            Get
                Return ResourceManager.GetString("ReadingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Reading folder:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ReadingFolder() As String
            Get
                Return ResourceManager.GetString("ReadingFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Searching result was written to file:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ResultWriteTo() As String
            Get
                Return ResourceManager.GetString("ResultWriteTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Searching text:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SearchingText() As String
            Get
                Return ResourceManager.GetString("SearchingText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Input the text for search, end with Ctrl+Z 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SearchText() As String
            Get
                Return ResourceManager.GetString("SearchText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Root folder for searching:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SearhingFolder() As String
            Get
                Return ResourceManager.GetString("SearhingFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Total files:  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Total() As String
            Get
                Return ResourceManager.GetString("Total", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
